### ISSUE TITLE
20210712 TODO

### ISSUE THREAD

**Issue by yhshin0** [transcendence42/ft_transcendence#102]
- 실시간 채팅 구현                                                          - yshin
- 실시간 게임 구현
- 사용자 인증 관련 쿠키 설정(프론트)
  - 커스텀 훅 만들기
    - 쿠키 받는 로직 필요(예상)
    - 각 페이지 들어갈 때 서버에 요청하는 로직 필요(예상) - 커스텀 훅 관련
- 사용자 인증 관련 쿠키 설정(백)
  - 쿠키 검증 로직 필요(예상)
- 로고 수정                                                                     - jwon
- 어드민 뷰 구성                                                             - jwon
- oauth 구현                                                                   - yechoi
- user computed field 구현                                            - holee
- 알람 organism 쿼리 받는 로직 구현                            - holee

**Comment by hochan222** [comment]
- [ ] admin: 7월 22일 (2day)
- [ ] profile: 7월 23일 (3day)
  - [ ] profile 친구 수락 테이블
  - [ ] profile 전적 테이블
  - [ ] profile 이미지 업로드
- [ ] chat
  - [ ] 채팅방 입장 메세지: 7월 21일 (1day)
    - [ ] 채팅방 입장 로직 front
    - [ ] 채팅방 입장 로직 back
  - [ ] 채팅방 떠나기: 7월 22일 (1day)
  - [ ] mute 
- [ ]
